### ISSUE TITLE
Output printed twice in 03-live-progress-and-capture-v3.go

### ISSUE THREAD

**Issue by vinaycalastry** [kjk/go-cookbook#2]
Line 48 of the code prints the output and the error(if any) from the external command's result. 

[go-cookbook/advanced-exec/03-live-progress-and-capture-v3.go](url)      

But I see that the output is printed first.
Then again under "out:"
![image](https://user-images.githubusercontent.com/25801794/50537471-004bc680-0b86-11e9-84fe-fff9700532d8.png)

I couldn't understand which part of the code is printing the first output.
Using: go version go1.11.2 windows/amd64

**Comment by kjk** [comment]
The commentary is in https://blog.kowalczyk.info/article/wOYk/advanced-command-execution-in-go-with-osexec.html

The example is showing how to connect program's output to stdout/stderr, so that you can see output while the program executes:
```
	stdoutIn, _ := cmd.StdoutPipe()
	stderrIn, _ := cmd.StderrPipe()

	var errStdout, errStderr error
	stdout := io.MultiWriter(os.Stdout, &stdoutBuf)
	stderr := io.MultiWriter(os.Stderr, &stderrBuf)
````
That is the first output.

And how to also capture the output. That is the second output:
```
	outStr, errStr := string(stdoutBuf.Bytes()), string(stderrBuf.Bytes())
	fmt.Printf("\nout:\n%s\nerr:\n%s\n", outStr, errStr)
````

**Comment by vinaycalastry** [comment]
Thank you so much. I read the MultiWriter code more carefully and I think I get it now.
